# Generated by Django 5.0.3 on 2024-03-21 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='file',
            name='DoubleSided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionID', models.CharField(max_length=100)),
                ('Amount', models.FloatField()),
                ('Status', models.CharField(max_length=100)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
