# Generated by Django 5.0.3 on 2024-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='PaymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
